# Generated by Django 5.0.2 on 2025-11-23 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sistema_escolar_api', '0003_alumnos_maestros'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventosAcademicos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_evento', models.CharField(max_length=255)),
                ('tipo_evento', models.CharField(choices=[('conferencia', 'Conferencia'), ('taller', 'Taller'), ('seminario', 'Seminario'), ('concurso', 'Concurso')], max_length=50)),
                ('fecha_realizacion', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('lugar', models.CharField(max_length=255)),
                ('publico_objetivo', models.CharField(choices=[('estudiantes', 'Estudiantes'), ('profesores', 'Profesores'), ('publico_general', 'Público general')], max_length=50)),
                ('programa_educativo', models.CharField(blank=True, choices=[('icc', 'Ingeniería en Ciencias de la Computación'), ('lcc', 'Licenciatura en Ciencias de la Computación'), ('iti', 'Ingeniería en Tecnologías de la Información')], max_length=50, null=True)),
                ('descripcion_breve', models.TextField(max_length=300)),
                ('cupo_maximo', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_responsable', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
